from . import hr_employee
from . import smarten_attendance_log
from . import smarten_unknown_log
from . import smarten_covered_log
from . import smarten_vip_log
from . import smarten_blocked_log
from . import smarten_visitor_pre_registration
from . import smarten_shift_schedule
from . import smarten_reid_embedding
from . import smarten_occupancy_snapshot
from . import smarten_unified_log
from . import res_config_settings